PLATFORM_WIDTH = 32
PLATFORM_HEIGHT = 32

map1 = [
       "csssssssssssssssssssssssssssssssssssssssssssssssssssssz",
       "d                                                     a",
       "d                                                     a",
       "d                               www                   a",
       "d            ww     wwwwwwwwww         ww  ww ww  wwwwa",
       "d                                   wwww              a",
       "dw                ww      w                           a",
       "d                             w                       a",
       "d                   www                               a",
       "d                                                     a",
       "d              w                                      a",
       "d      www                                            a",
       "d                                                     a",
       "d   wwwwwwwwwww                                       a",
       "d                                                     a",
       "d                w                                    a",
       "d                   ww                                a",
       "d                          w                          a",
       "d                     w                              wa",
       "d                             w                       a",
       "d                                                    wa",
       "d                               w                     a",
       "d                                                    wa",
       "d                           w                         a",
       "d                                                     a",
       "d                                ww                   a",
       "d                                                     a",
       "d                                                     a",
       "d                                     www             a",
       "d                                                     a",
       "d                                                     a",
       "ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwq"]