PLATFORM_WIDTH = 32
PLATFORM_HEIGHT = 32

map1 = [
       "csssssssssssssssssssssssssssssssssz",
       "d                                 a",
       "d                                 a",
       "d                                 a",
       "d            ww     wwwwwwwwww    a",
       "d                                wa",
       "dw                ww      w       a",
       "d                             w   a",
       "d                   www           a",
       "d                                 a",
       "d              w                  a",
       "d      www                        a",
       "d                                 a",
       "d   wwwwwwwwwww                   a",
       "d                                 a",
       "d                w                a",
       "d                   ww            a",
       "d                         w       a",
       "d                     w          wa",
       "d                        w        a",
       "d                                wa",
       "d                          w      a",
       "d                                wa",
       "d                        w        a",
       "d                                 a",
       "ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwq"]